name: blaey_app
description: Um app Flutter com 4 páginas e um menu inferior.

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.1.0
  flame: ^1.0.0  # Atualize para a versão mais recente
  carousel_slider: ^4.2.1
  flutter_screenutil: ^5.8.4
  rive: ^0.11.4
  lottie: ^2.5.0
  image_picker: ^1.0.1
  flutter_spinkit: ^5.2.0
  animated_bottom_navigation_bar: ^1.2.0
  cupertino_icons: ^1.0.5
  persistent_bottom_nav_bar: ^5.0.2
  flutter_animate: ^4.2.0
  flutter_emoji: ^2.5.1
  audioplayers: ^5.2.1
  firebase_core: ^2.0.0
  firebase_messaging: ^14.2.0
  firebase_analytics: ^10.4.5
  firebase_crashlytics: ^3.4.0
  firebase_auth: ^4.7.2
  firebase_auth_web: ^5.8.13
  firebase_database: ^10.2.5
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  google_sign_in: ^6.2.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^14.1.5 # Versão anterior
  intl: ^0.18.1
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.2
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.12
  package_info_plus: ^4.0.0
  sizer: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-RegularItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900

  assets:
    - assets/icons/icon_transparente.png
    - assets/icons/app_icon.png
    - assets/jogos/dama.png
    - assets/jogos/xadrez.png
    - assets/jogos/ludo.png
    - assets/jogos/truco.png
    - assets/jogos/jogo_da_velha.png
    - assets/jogos/double.png
    - assets/jogos/berasso.png
    - assets/jogos/super.png
    - assets/jogos/rei.png
    - assets/jogos/banner1.png
    - assets/jogos/banner2.png
    - assets/jogos/banner3.png
    - assets/jogos/banner4.png
    - assets/jogos/torneios.png
    - assets/jogos/eventos.png
    - assets/jogos/maratonas.png
    - assets/images/pesquisa.png
    - assets/icons/logoblaey.png
    - assets/icons/user.png
    - assets/icons/moeda.png
    - assets/animations/level_up.riv
    - assets/images/opponent_photo.png
    - assets/images/user_photo.png
    - assets/jogos/dama_vermelho.png
    - assets/jogos/damatab.png
    - assets/jogos/chesstab.png
    - assets/jogos/dama_azul.png
    - assets/jogos/rei_azul.png
    - assets/jogos/rei_vermelho.png
    - assets/jogos/rei.png
    - assets/images/fundo_preto.png
    - assets/icons/plus.png
    - assets/icons/fundo_mensagem.png
    - assets/icons/perfil.png
    - assets/icons/filter.png
    - assets/users/oponente.png
    - assets/users/oponente1.png
    - assets/users/oponente2.png
    - assets/users/oponente3.png
    - assets/users/oponente4.png
    - assets/users/oponente5.png
    - assets/users/oponente6.png
    - assets/icons/vs.png
    - assets/icons/trofeu.png
    - assets/meme/meme1.png
    - assets/meme/meme2.png
    - assets/meme/meme3.png
    - assets/meme/meme4.png
    - assets/meme/meme5.png
    - assets/icons/convite.png
    - assets/icons/loja.png
    - assets/icons/bonus.png
    - assets/icons/recargapro.png
    - assets/som/move_sound.mp3
    - assets/som/moeda.mp3
    - assets/som/captura.mp3
    - assets/jogos/chess/peaopreto.png
    - assets/jogos/chess/torrepreto.png
    - assets/jogos/chess/cavalopreto.png
    - assets/jogos/chess/bispopreto.png
    - assets/jogos/chess/damapreto.png
    - assets/jogos/chess/reipreto.png
    - assets/jogos/chess/peaobranco.png
    - assets/jogos/chess/torrebranco.png
    - assets/jogos/chess/cavalobranco.png
    - assets/jogos/chess/bispobranco.png
    - assets/jogos/chess/damabranco.png
    - assets/jogos/chess/reibranco.png
    - assets/jogos/chess/tabuleirochess.png